Landing page animation 2023
HopHacks/hophacks-flask pull request #300
Opened 2023-06-07 06:53 UTC by nishikar12

made landing page animation for 2023
notes:
The animation looks good on mobile and normal sized screens, but might look a little scuffed on "medium sized" windows.
Looks very weird on safari, and not sure why. Can you let me know if its weird on your end too?

2023-06-11 19:29 UTC, AkhilDeo requested changes

2023-06-11 19:29 UTC, AkhilDeo commented on frontend/src/components/home/AboutSeparation.jsx
Why remove clouds?

2023-06-11 19:29 UTC, AkhilDeo commented on frontend/src/components/home/About.jsx
The logo in the about section is partially obstructed by the banner. Besides that, nice!
<img width="1728" alt="Screen Shot 2023-06-11 at 2 26 01 PM" src="https://github.com/HopHacks/hophacks-flask/assets/43221536/e59e2a1a-64ee-45d1-acf3-4e415de9ce2a">

2023-06-12 02:14 UTC, nishikar12 commented on frontend/src/components/home/AboutSeparation.jsx
shoot it was being annoying while I was testing so I disabled it, just added it back. whoops

2023-06-16 13:49 UTC, merged